services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo

  scripts:
    build:
      context: ./scripts
    volumes:
      - ./public:/public
      - ./scripts:/scripts
    env_file:
      - ./scripts/.env
    depends_on:
      - mongo
    restart: on-failure
    command: ["python", "main.py"]

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootusername
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

volumes:
  mongo-data:
